import React from "react";
import { Helmet } from "react-helmet-async";

const faqs = [
  {
    q: "Is Ravlo really free?",
    a: "Yes! Ravlo is a side project and will always be free to use. There are no hidden costs, premium tiers, or limitations.",
  },
  {
    q: "Do you store my LinkedIn data or posts?",
    a: "No, nothing you write or generate is stored or sent to any server. All content is processed locally in your browser, and drafts are saved only on your device using localStorage.",
  },
  {
    q: "Can I use Ravlo on mobile?",
    a: "Yes, Ravlo is fully responsive and works great on mobile devices. The interface adapts to all screen sizes, and all features are accessible on smartphones and tablets.",
  },
  {
    q: "Who built Ravlo?",
    a: "Ravlo was built by Ashutosh Rai as a personal side project. You can connect with him on LinkedIn at @ashusomehow.",
  },
  {
    q: "How do I contact support?",
    a: "Email ashusomehow@gmail.com or visit the 'Buy Me a Coffee' page to support the project and get in touch.",
  },
  {
    q: "What are hook templates and how do they work?",
    a: "Hook templates are proven opening lines that grab attention and increase engagement. Ravlo offers three categories: Curiosity hooks (create intrigue), Story hooks (narrative openings), and Provoke hooks (spark discussion). You can also choose 'No Hook' for a category-specific engaging opening.",
  },
  {
    q: "Can I use the generated content on other platforms?",
    a: "Absolutely! The content generated by Ravlo can be used on any platform - LinkedIn, Twitter, Facebook, blogs, or anywhere else. The formatting options also work across most platforms.",
  },
  {
    q: "How does the Post Formatter work?",
    a: "The Post Formatter uses Unicode characters to create bold, italic, and underlined text that persists when copied to LinkedIn, Notes, or any other platform. Select text and click B/I/U buttons to apply formatting, or use the reset button to clear all formatting.",
  },
  {
    q: "Are my drafts saved permanently?",
    a: "Drafts are saved in your browser's localStorage, which means they persist until you clear your browser data or manually delete them. They're stored locally on your device, not on any server.",
  },
  {
    q: "What's the difference between Concise and Story-Rich posts?",
    a: "Concise posts are shorter, punchy versions perfect for quick engagement. Story-Rich posts are longer, more detailed versions with narrative elements that work well for thought leadership and deeper content.",
  },
  {
    q: "Can I customize the AI generation settings?",
    a: "Yes! You can control emoji usage, hashtag inclusion, bullet point styling, and tone selection. The AI adapts to your preferences to generate personalized content.",
  },
  {
    q: "Is there a limit on how many posts I can generate?",
    a: "No limits! You can generate as many posts as you want. The AI is powered by Google's Gemini API and processes requests efficiently.",
  },
  {
    q: "How do I get the best results from Ravlo?",
    a: "For best results: 1) Provide specific, detailed topics 2) Choose appropriate hook categories 3) Use the formatting tools to enhance your posts 4) Save and reuse successful drafts 5) Experiment with different tones and settings.",
  },
  {
    q: "Can I edit posts after they're generated?",
    a: "Yes! All generated posts can be edited in the Post Formatter. You can modify text, apply formatting, and save as new drafts. The 'Copy to Formatter' button makes this process seamless.",
  },
  {
    q: "What makes Ravlo different from other AI writing tools?",
    a: "Ravlo is specifically designed for LinkedIn with proven hook templates, cross-platform formatting that actually works, local data processing for privacy, and a streamlined workflow from generation to posting. Plus, it's completely free!",
  },
  {
    q: "Do I need a LinkedIn extension or plugin?",
    a: "No! Ravlo works entirely in your browser. You generate content here, copy it, and paste it directly into LinkedIn. No extensions, plugins, or account connections required.",
  },
  {
    q: "How often should I post on LinkedIn?",
    a: "Consistency is key! Most professionals post 2-5 times per week. Ravlo helps you maintain this consistency by making content creation faster and easier.",
  },
  {
    q: "Can I use Ravlo for business accounts?",
    a: "Absolutely! Ravlo works great for both personal and business LinkedIn accounts. The professional tone options and formatting tools are perfect for company pages and business content.",
  },
  {
    q: "What if the AI generates content I don't like?",
    a: "Simply regenerate! You can generate multiple versions until you get content you're happy with. You can also edit any generated content in the Post Formatter to make it perfect.",
  },
  {
    q: "Is my content original and plagiarism-free?",
    a: "Yes! Ravlo generates unique content based on your specific topics and inputs. The AI creates original text each time, ensuring your posts are unique and authentic.",
  }
];

const FAQ = () => (
  <>
    <Helmet>
      <title>FAQ – Ravlo LinkedIn Tool</title>
      <meta name="description" content="Find answers to common questions about Ravlo's AI LinkedIn post generation, formatting tools, and draft management features." />
      <meta name="keywords" content="Ravlo FAQ, LinkedIn tool questions, AI post generation help, formatting support" />
      <meta property="og:title" content="FAQ – Ravlo LinkedIn Tool" />
      <meta property="og:description" content="Find answers to common questions about Ravlo's AI LinkedIn post generation, formatting tools, and draft management features." />
      <meta property="og:image" content="/og-preview.png" />
      <meta property="og:url" content="https://www.ravlo.pro/faq" />
      <meta property="og:type" content="website" />
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:title" content="FAQ – Ravlo LinkedIn Tool" />
      <meta name="twitter:description" content="Find answers to common questions about Ravlo's AI LinkedIn post generation, formatting tools, and draft management features." />
      <meta name="twitter:image" content="/og-preview.png" />
    </Helmet>
    <div className="max-w-2xl mx-auto py-12 px-4">
      <h1 className="text-3xl font-bold mb-8">Frequently Asked Questions</h1>
      <div className="space-y-4">
        {faqs.map((faq, i) => (
          <details key={i} className="border rounded p-4 group transition-shadow hover:shadow-md">
            <summary className="font-semibold cursor-pointer group-open:text-primary transition-colors">{faq.q}</summary>
            <div className="mt-2 text-muted-foreground">{faq.a}</div>
          </details>
        ))}
      </div>
    </div>
  </>
);

export default FAQ; 